Traceback (most recent call last):
  File "/Users/tconnolly/opt/miniconda3/envs/data-book/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/tconnolly/opt/miniconda3/envs/data-book/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/tconnolly/opt/miniconda3/envs/data-book/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/tconnolly/opt/miniconda3/envs/data-book/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/tconnolly/opt/miniconda3/envs/data-book/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/Users/tconnolly/opt/miniconda3/envs/data-book/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/tconnolly/opt/miniconda3/envs/data-book/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/tconnolly/opt/miniconda3/envs/data-book/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
fvalues = exponential_growth(np.array([0,1]),10,1)
print(fvalues)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Input [0;32mIn [9][0m, in [0;36m<cell line: 1>[0;34m()[0m
[0;32m----> 1[0m fvalues [38;5;241m=[39m [43mexponential_growth[49m[43m([49m[43mnp[49m[38;5;241;43m.[39;49m[43marray[49m[43m([49m[43m[[49m[38;5;241;43m0[39;49m[43m,[49m[38;5;241;43m1[39;49m[43m][49m[43m)[49m[43m,[49m[38;5;241;43m10[39;49m[43m,[49m[38;5;241;43m1[39;49m[43m)[49m
[1;32m      2[0m [38;5;28mprint[39m(fvalues)

Input [0;32mIn [7][0m, in [0;36mexponential_growth[0;34m(t, a1, a2)[0m
[1;32m      2[0m [38;5;124;03m'''inputs:[39;00m
[1;32m      3[0m [38;5;124;03mt - vector of times[39;00m
[1;32m      4[0m [38;5;124;03ma1 - initial population at time 0[39;00m
[0;32m   (...)[0m
[1;32m      7[0m [38;5;124;03mreturns: modeled population based on exponential growth[39;00m
[1;32m      8[0m [38;5;124;03m'''[39;00m
[1;32m      9[0m [38;5;66;03m# insert code here[39;00m
[0;32m---> 10[0m [38;5;28;01mreturn[39;00m [43mf[49m

[0;31mNameError[0m: name 'f' is not defined
NameError: name 'f' is not defined

